baseURL = "https://coursinfo.ca/420-5D4/ansible/"
languageCode = "fr-ca"
DefaultContentLanguage = "fr"
theme = "hugo-theme-learn"
[params]
themeVariant = "blue"
titleSeparator = ""
disableLandingPageButton = true
landingPageURL = "https://coursinfo.ca/420-5D4/ansible/"
landingPageName = "<i class='fas fa-home'></i> Accueil"
disableSearch = true
disableInlineCopyToClipBoard = true
editURL = ""
author = "Antoine Tohmé"
