baseURL = "https://wonderful-rock-09d742710.7.azurestaticapps.net/"
languageCode = "fr-ca"
DefaultContentLanguage = "fr"
theme = "hugo-theme-learn"
[params]
themeVariant = "blue"
titleSeparator = ""
disableLandingPageButton = true
landingPageURL = "https://wonderful-rock-09d742710.7.azurestaticapps.net/"
landingPageName = "<i class='fas fa-home'></i> Accueil"
disableSearch = true
disableInlineCopyToClipBoard = true
editURL = ""
author = "Antoine Tohmé"
